### ISSUE TITLE
Re: Issue 243: Remove cluster-client-grpc samples?

### ISSUE THREAD

**Issue by sam-byng** [apache/pekko-samples#16]
I raised an issue on akka-samples re: the outdated cluster-client example

https://github.com/akka/akka-samples/issues/280#issuecomment-1473366893

Response was that this was intended for initial migration onto the grpc cluster client, and isn't relevant now. 

Can we remove this too?

Side note: are we 'allowed' to go and communicate on the Akka repositories when we see bugs/ have questions?

**Comment by sam-byng** [comment]
"""The cluster client was a sample to show how to move off the deprecated cluster-client feature back when Akka 2.6.0 was released, trying to provide the same behavior but over gRPC, it is not really relevant for anything else, so I think we should just drop the sample from samples main instead."""

We are still on 2.6.x , while akka-samples is up to 2.8.0 , so perhaps this is still relevant?

**Comment by pjfanning** [comment]
We'll be reluctant to remove samples if they are at all useful. If there is a newer better way way, we can use the sample readme to highlight the new approach and maybe someone will have time to provide a new sample for the new better way.
